#端口
server:
  port: 8200

spring:
  datasource:
#    url: jdbc:mysql://47.98.232.129:3306/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
#    公司密码
    password: root
#    家里密码
#    password: 123456
    driverClassName: com.mysql.jdbc.Driver

    #连接池的配置信息
    #初始化大小,最小,最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 6000
    #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: true
    testOnBorrow: fales
    testOnReturn: fales
    #打开PSCache,并且制定每个连接上PSCache的大小
    poolPreparedDtatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters,去掉后监控界面SQL无法统计,‘wall’用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    shiro:
      host: 127.0.0.1
      port: 6379
      timeout: 0
      password: 123456


#MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cx.prototype.mode.entity
  global-config:
    #主键类型 0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰转下划线
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    #使用驼峰法映射属性
    map-underscore-to-camel-case: true
    #全局缓存
    cache-enabled: false
    #日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #使用jdbc的getGeneratedKeys获取数据库自增主键值
    use-generated-keys: true